/**
 * Verified Agronomic Integrated Pest Management (IPM) Tiers
 * Covers all 38 PlantVillage crops and foliar diseases with full English and Hindi localization.
 */
export const TREATMENT_TIERS = [
  {
    classId: 'Apple___Apple_scab',
    cropName: 'Apple',
    cropNameHi: 'सेब',
    diseaseName: 'Apple Scab (Venturia inaequalis)',
    diseaseNameHi: 'सेब — पपड़ी रोग (Apple Scab)',
    organicAction: 'Rake and destroy fallen leaves to reduce overwintering ascospore inoculum. Apply liquid lime sulfur or potassium bicarbonate sprays during green tip stage.',
    organicActionHi: 'गिरे हुए पुराने पत्तों को इकट्ठा करके जलाएं ताकि फफूंद न फैले। हरी कली फूटने पर चूना-सल्फर या बेकिंग सोडा के घोल का छिड़काव करें।',
    chemicalSpray: 'Apply protective Captan or Mancozeb sprays at tight cluster, or curative Difenoconazole / Myclobutanil within 72 hours of an infection period.',
    chemicalSprayHi: 'कैप्टान (Captan) 2 ग्राम या डाइफेनोकोनाज़ोल (Difenoconazole) 1 मिली प्रति लीटर पानी में मिलाकर 10-12 दिन पर छिड़कें।'
  },
  {
    classId: 'Apple___Black_rot',
    cropName: 'Apple',
    cropNameHi: 'सेब',
    diseaseName: 'Black Rot (Diplodia seriata)',
    diseaseNameHi: 'सेब — काला सड़न रोग (Black Rot)',
    organicAction: 'Prune out dead wood, cankers, and remove all mummified fruit from trees and orchard floor. Apply copper octanoate before bud break.',
    organicActionHi: 'पेड़ की सूखी व सड़ी हुई टहनियों को काटकर हटाएं और कटे स्थान पर बोर्डो पेस्ट लगाएं।',
    chemicalSpray: 'Apply Thiophanate-methyl combined with Captan from silver tip stage through petal fall and summer cover sprays.',
    chemicalSprayHi: 'थियोफैनेट मिथाइल (Thiophanate-methyl) या मैंकोज़ेब (Mancozeb) का 2.5 ग्राम प्रति लीटर पानी में छिड़काव करें।'
  },
  {
    classId: 'Apple___Cedar_apple_rust',
    cropName: 'Apple',
    cropNameHi: 'सेब',
    diseaseName: 'Cedar Apple Rust (Gymnosporangium)',
    diseaseNameHi: 'सेब — रतुआ रोग (Cedar Apple Rust)',
    organicAction: 'Remove nearby Eastern red cedar / juniper galls within orchard perimeter if feasible. Apply sulfur or neem oil sprays at bud break.',
    organicActionHi: 'बगीचे के आसपास मौजूद जंगली झाड़ियों को साफ करें। कली फूटते समय नीम तेल या सल्फर का छिड़काव करें।',
    chemicalSpray: 'Apply Myclobutanil, Mancozeb, or Propiconazole starting at pink bud stage through petal fall at 7-10 day intervals.',
    chemicalSprayHi: 'माइक्लोबुटानिल (Myclobutanil) या प्रोपिकोनाज़ोल (Propiconazole) का 1 मिली प्रति लीटर पानी में छिड़काव करें।'
  },
  {
    classId: 'Apple___healthy',
    cropName: 'Apple',
    cropNameHi: 'सेब',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'No disease detected. Maintain balanced nitrogen-potassium soil nutrition, annual pruning, and routine canopy air circulation.',
    organicActionHi: 'फसल एकदम स्वस्थ है। पेड़ों की समय पर कटाई-छंटाई और हल्की सिंचाई जारी रखें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी रासायनिक दवा की कोई जरूरत नहीं है।'
  },
  {
    classId: 'Blueberry___healthy',
    cropName: 'Blueberry',
    cropNameHi: 'ब्लूबेरी',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Foliage is healthy. Maintain acidic soil pH (4.5–5.2), pine bark mulching, and steady drip irrigation.',
    organicActionHi: 'फसल स्वस्थ है। मिट्टी में अम्लीयता (pH 4.5–5.2) बनाए रखें और ड्रिप से पानी दें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'कोई रासायनिक दवा न डालें।'
  },
  {
    classId: 'Cherry_(including_sour)___Powdery_mildew',
    cropName: 'Cherry',
    cropNameHi: 'चेरी',
    diseaseName: 'Powdery Mildew (Podosphaera clandestina)',
    diseaseNameHi: 'चेरी — चूर्णिल फफूंद (Powdery Mildew)',
    organicAction: 'Prune interior suckers to maximize canopy sunlight and airflow. Apply wettable sulfur, horticultural mineral oil, or potassium bicarbonate.',
    organicActionHi: 'पेड़ के अंदरूनी हिस्से की छंटाई करें ताकि धूप और हवा पहुंचे। घुलनशील गंधक (सल्फर) 2 ग्राम प्रति लीटर पानी में छिड़कें।',
    chemicalSpray: 'Apply Quinoxyfen, Fluopyram, or Myclobutanil when terminal shoot growth reaches 2 inches, repeated every 10–14 days.',
    chemicalSprayHi: 'माइक्लोबुटानिल या हेक्साकोनाज़ोल (1 मिली प्रति लीटर) का 12 दिन के अंतराल पर छिड़काव करें।'
  },
  {
    classId: 'Cherry_(including_sour)___healthy',
    cropName: 'Cherry',
    cropNameHi: 'चेरी',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'No disease symptoms present. Maintain orchard sanitation, balanced fertilizing, and clean bird netting.',
    organicActionHi: 'पौधे स्वस्थ हैं। संतुलित खाद और साफ-सफाई बनाए रखें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी दवा की जरूरत नहीं है।'
  },
  {
    classId: 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
    cropName: 'Corn (Maize)',
    cropNameHi: 'मक्का',
    diseaseName: 'Cercospora Gray Leaf Spot',
    diseaseNameHi: 'मक्का — धब्बा रोग (Gray Leaf Spot)',
    organicAction: 'Implement a 2-year crop rotation with non-host legumes (soybean) and deep-till crop residue to accelerate residue decomposition.',
    organicActionHi: 'फसल चक्र अपनाएं (मक्का के बाद दलहनी फसलें लगाएं)। खेत में पिछली फसल के डंठलों को गहरी जुताई कर दबाएं।',
    chemicalSpray: 'Apply Strobilurin + Triazole premix (e.g., Pyraclostrobin + Fluxapyroxad, or Azoxystrobin + Propiconazole) at VT to R1 tasseling growth stage.',
    chemicalSprayHi: 'एज़ोक्सीस्ट्रोबिन + प्रोपिकोनाज़ोल 1 मिली प्रति लीटर पानी में मिलाकर बालियां निकलते समय छिड़कें।'
  },
  {
    classId: 'Corn_(maize)___Common_rust_',
    cropName: 'Corn (Maize)',
    cropNameHi: 'मक्का',
    diseaseName: 'Common Rust (Puccinia sorghi)',
    diseaseNameHi: 'मक्का — रतुआ / गेरुआ रोग (Common Rust)',
    organicAction: 'Plant rust-resistant hybrid varieties early in the season. Destroy volunteer corn plants that harbor urediniospores.',
    organicActionHi: 'रोग-रोधी बीज की समय पर बुवाई करें। खेत के आसपास उगे अनचाहे मक्के के पौधों को नष्ट करें।',
    chemicalSpray: 'Apply Pyraclostrobin, Azoxystrobin, or Propiconazole when rust pustules appear on lower leaves prior to tasseling.',
    chemicalSprayHi: 'पायराक्लोस्ट्रोबिन या मैंकोज़ेब (2.5 ग्राम प्रति लीटर) का पत्तों पर फफोले दिखते ही छिड़काव करें।'
  },
  {
    classId: 'Corn_(maize)___Northern_Leaf_Blight',
    cropName: 'Corn (Maize)',
    cropNameHi: 'मक्का',
    diseaseName: 'Northern Leaf Blight (Exserohilum turcicum)',
    diseaseNameHi: 'मक्का — झुलसा रोग (Northern Leaf Blight)',
    organicAction: 'Practice minimum 1-year rotation away from corn. Utilize resistant hybrids containing Ht gene alleles and deep-plow stubble post-harvest.',
    organicActionHi: 'फसल चक्र अपनाएं। रोगरोधी किस्मों की बुवाई करें और खेत की गहरी जुताई करें।',
    chemicalSpray: 'Apply systemic Azoxystrobin + Difenoconazole or Pyraclostrobin at early silking if cigar-shaped lesions develop on lower leaves.',
    chemicalSprayHi: 'डाइफेनोकोनाज़ोल या मैंकोज़ेब का 2 ग्राम प्रति लीटर पानी में पत्तों पर लंबे धब्बे दिखने पर छिड़काव करें।'
  },
  {
    classId: 'Corn_(maize)___healthy',
    cropName: 'Corn (Maize)',
    cropNameHi: 'मक्का',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Vigorous chlorophyll tissue detected. Maintain balanced NPK split applications and monitor for corn borer larvae.',
    organicActionHi: 'पौधा एकदम स्वस्थ व हरा-भरा है। यूरिया की संतुलित मात्रा दें और तना छेदक कीट की निगरानी करें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी रासायनिक दवा की आवश्यकता नहीं है।'
  },
  {
    classId: 'Grape___Black_rot',
    cropName: 'Grape',
    cropNameHi: 'अंगूर',
    diseaseName: 'Black Rot (Guignardia bidwellii)',
    diseaseNameHi: 'अंगूर — काला सड़न रोग (Black Rot)',
    organicAction: 'Remove and burn all mummified fruit berries from trellises during winter dormancy. Open canopy via shoot positioning and leaf pulling around fruit zones.',
    organicActionHi: 'बेलों पर लटके सूखे और काले सड़े हुए गुच्छों को तोड़कर जलाएं। हवा के बहाव के लिए पत्तों की छंटाई करें।',
    chemicalSpray: 'Apply Mancozeb or Ziram from 1-inch shoot growth until 4 weeks after bloom. Switch to Myclobutanil or Tebuconazole if active lesions appear.',
    chemicalSprayHi: 'फूल आने से पहले और बाद में मैंकोज़ेब (2.5 ग्राम) या टेबुकोनाज़ोल (1 मिली प्रति लीटर) का छिड़काव करें।'
  },
  {
    classId: 'Grape___Esca_(Black_Measles)',
    cropName: 'Grape',
    cropNameHi: 'अंगूर',
    diseaseName: 'Esca / Black Measles (Fungal Trunk Complex)',
    diseaseNameHi: 'अंगूर — एस्का रोग (Black Measles)',
    organicAction: 'Prune during dry late-dormant weather to reduce spore entry into pruning wounds. Paint large wounds with wound sealant paste or Trichoderma harzianum.',
    organicActionHi: 'कटाई-छंटाई सूखी धूप में करें। मोटे तने के कटे हिस्सों पर बोर्डो लेप या घाव भरने वाला पेस्ट लगाएं।',
    chemicalSpray: 'No single curable spray exists for internal trunk decay; protect fresh pruning wounds with Thiophanate-methyl or Boron-acrylic sealer.',
    chemicalSprayHi: 'तने के अंदरूनी सड़न पर छिड़काव असर नहीं करता; कटाई के तुरंत बाद तने पर कॉपर या थियोफैनेट मिथाइल का लेप लगाएं।'
  },
  {
    classId: 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
    cropName: 'Grape',
    cropNameHi: 'अंगूर',
    diseaseName: 'Leaf Blight (Pseudocercospora vitis)',
    diseaseNameHi: 'अंगूर — पत्ती झुलसा रोग (Leaf Blight)',
    organicAction: 'Prune infected canopy foliage to improve ventilation. Apply copper hydroxide or fixed copper fungicides immediately post-harvest.',
    organicActionHi: 'जमीन से सटे रोगी पत्तों को हटाएं। कटाई के बाद कॉपर ऑक्सीक्लोराइड का छिड़काव करें।',
    chemicalSpray: 'Apply broad-spectrum Mancozeb, Copper oxychloride, or Carbendazim at 14-day intervals during warm humid weather.',
    chemicalSprayHi: 'मैंकोज़ेब (2.5 ग्राम) या कार्बेन्डाजिम (1 ग्राम प्रति लीटर पानी) का 14 दिन पर छिड़काव करें।'
  },
  {
    classId: 'Grape___healthy',
    cropName: 'Grape',
    cropNameHi: 'अंगूर',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Vines show optimal chlorophyll vigor. Maintain regulated deficit irrigation, vine training, and shoot thinning.',
    organicActionHi: 'अंगूर की बेलें बहुत अच्छी और स्वस्थ हैं। समय पर शाखाओं को सहारा दें और संतुलित सिंचाई करें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी रासायनिक दवा की जरूरत नहीं है।'
  },
  {
    classId: 'Orange___Haunglongbing_(Citrus_greening)',
    cropName: 'Orange (Citrus)',
    cropNameHi: 'संतरा / नींबू',
    diseaseName: 'Huanglongbing / Citrus Greening (Candidatus Liberibacter)',
    diseaseNameHi: 'संतरा — साइट्रस ग्रीनिंग (Citrus Greening)',
    organicAction: 'Inspect and suppress Asian Citrus Psyllid (ACP) vectors using yellow sticky traps and releases of Tamarixia radiata parasitoid wasps. Rogue out symptomatic trees to curb spread.',
    organicActionHi: 'सिट्रस साइला कीट को पीले चिपचिपे कार्ड लगाकर रोकें। अत्यधिक रोगी पेड़ों को काटकर नष्ट करें ताकि बाकी पेड़ बचें।',
    chemicalSpray: 'Vector control: Apply systemic Imidacloprid as a soil drench in young groves, or foliar Fenpropathrin / Thiamethoxam during active psyllid flush.',
    chemicalSprayHi: 'कीट रोकथाम: इमिडाक्लोप्रिड 0.5 मिली या थायमेथॉक्सम 0.3 ग्राम प्रति लीटर पानी में मिलाकर नई कोपलें आते समय छिड़कें।'
  },
  {
    classId: 'Peach___Bacterial_spot',
    cropName: 'Peach',
    cropNameHi: 'आड़ू',
    diseaseName: 'Bacterial Spot (Xanthomonas arboricola)',
    diseaseNameHi: 'आड़ू — जीवाणु धब्बा (Bacterial Spot)',
    organicAction: 'Avoid high-nitrogen fertilizer spikes that induce lush susceptible tissue. Apply fixed copper sulfate during late dormancy (bud swell).',
    organicActionHi: 'बहुत ज्यादा यूरिया देने से बचें। कली फूलने के समय कॉपर सल्फेट का हल्का घोल छिड़कें।',
    chemicalSpray: 'Apply Oxytetracycline (Mycoshield) or copper hydroxide at low rates from petal fall through shuck split at 7-10 day intervals.',
    chemicalSprayHi: 'स्ट्रेप्टोसाइक्लिन (1 ग्राम प्रति 10 लीटर पानी) + कॉपर ऑक्सीक्लोराइड (25 ग्राम) मिलाकर छिड़काव करें।'
  },
  {
    classId: 'Peach___healthy',
    cropName: 'Peach',
    cropNameHi: 'आड़ू',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Foliage is clean and unblemished. Maintain open-center vase pruning, balanced watering, and dormant spray schedule.',
    organicActionHi: 'पेड़ बिल्कुल स्वस्थ हैं। पर्याप्त धूप और संतुलित पानी बनाए रखें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी रासायनिक दवा की आवश्यकता नहीं है।'
  },
  {
    classId: 'Pepper,_bell___Bacterial_spot',
    cropName: 'Bell Pepper',
    cropNameHi: 'शिमला मिर्च',
    diseaseName: 'Bacterial Spot (Xanthomonas campestris)',
    diseaseNameHi: 'शिमला मिर्च — जीवाणु धब्बा (Bacterial Spot)',
    organicAction: 'Use certified disease-free seeds soaked in 50°C hot water for 25 minutes. Drench with copper octanoate and Bacillus subtilis bio-bactericide.',
    organicActionHi: 'रोग-मुक्त प्रमाणित बीज इस्तेमाल करें। पौधे के ऊपर से पानी डालने के बजाय जड़ में पानी दें ताकि पत्ते सूखे रहें।',
    chemicalSpray: 'Apply Copper Hydroxide mixed with Mancozeb (to overcome copper resistance) on a 7-day schedule during rainy, humid periods.',
    chemicalSprayHi: 'कॉपर हाइड्रोक्साइड (2 ग्राम) + मैंकोज़ेब (2 ग्राम प्रति लीटर पानी) का बारिश के मौसम में 7 दिन के अंतराल पर छिड़काव करें।'
  },
  {
    classId: 'Pepper,_bell___healthy',
    cropName: 'Bell Pepper',
    cropNameHi: 'शिमला मिर्च',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'No action required. Maintain balanced drip irrigation, calcium supplementation (prevent blossom end rot), and pest scouting.',
    organicActionHi: 'फसल एकदम स्वस्थ है। कैल्शियम की सही मात्रा दें ताकि फल नीचे से न सड़े, और ड्रिप से सिंचाई करें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी दवा की जरूरत नहीं है।'
  },
  {
    classId: 'Potato___Early_blight',
    cropName: 'Potato',
    cropNameHi: 'आलू',
    diseaseName: 'Early Blight (Alternaria solani)',
    diseaseNameHi: 'आलू — अगेती झुलसा (Early Blight)',
    organicAction: 'Practice minimum 3-year crop rotation with non-solanaceous crops. Apply organic copper or Serenade (Bacillus amyloliquefaciens) preventive drench.',
    organicActionHi: 'आलू की फसल में 3 साल का फसल चक्र अपनाएं। जमीन से लगे रोगग्रस्त पत्तों को हटा दें।',
    chemicalSpray: 'Apply Chlorothalonil or Mancozeb preventively, or switch to Boscalid / Difenoconazole upon seeing concentric target lesions.',
    chemicalSprayHi: 'क्लोरोथैलोनिल या मैंकोज़ेब (2.5 ग्राम प्रति लीटर) का छिड़काव करें। धब्बे बढ़ने पर डाइफेनोकोनाज़ोल का छिड़काव करें।'
  },
  {
    classId: 'Potato___Late_blight',
    cropName: 'Potato',
    cropNameHi: 'आलू',
    diseaseName: 'Late Blight (Phytophthora infestans)',
    diseaseNameHi: 'आलू — पछेती झुलसा (Late Blight)',
    organicAction: 'CRITICAL OUTBREAK RISK: Immediately rogue out and bag infected plants. Avoid sprinkler irrigation; burn haulms 2 weeks before harvest.',
    organicActionHi: '🚨 अत्यंत खतरनाक रोग! रोगी पौधों को तुरंत उखाड़कर जमीन में दबाएं। खेत में जलभराव बिल्कुल न होने दें।',
    chemicalSpray: 'Apply systemic Cymoxanil + Mancozeb, Dimethomorph, or Metalaxyl-M (Ridomil Gold) immediately. Alternate modes of action to prevent resistance.',
    chemicalSprayHi: 'तुरंत साइमोक्सानिल + मैंकोज़ेब (2.5 ग्राम) या रिडोमिल गोल्ड (Metalaxyl-M) का तुरंत छिड़काव करें।'
  },
  {
    classId: 'Potato___healthy',
    cropName: 'Potato',
    cropNameHi: 'आलू',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Foliage exhibits vigorous chlorophyll density. Hill soil around stems to protect tubers from greening and maintain uniform soil moisture.',
    organicActionHi: 'पौधे बहुत अच्छे और स्वस्थ हैं। पौधों पर मिट्टी चढ़ाएं ताकि आलू धूप से हरे न हों और समान नमी रखें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी दवा की कोई आवश्यकता नहीं है।'
  },
  {
    classId: 'Raspberry___healthy',
    cropName: 'Raspberry',
    cropNameHi: 'रसभरी',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Canes show robust growth. Maintain trellising, cane thinning, organic straw mulch, and drip irrigation.',
    organicActionHi: 'पौधे स्वस्थ हैं। सूखी घास की मल्चिंग करें और ड्रिप से संतुलित पानी दें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'कोई दवा न डालें।'
  },
  {
    classId: 'Soybean___healthy',
    cropName: 'Soybean',
    cropNameHi: 'सोयाबीन',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Excellent vegetative stand. Maintain rhizobium nodulation check, timely weeding, and soil moisture during pod-fill.',
    organicActionHi: 'फसल एकदम स्वस्थ व हरी-भरी है। खेत से खरपतवार निकालते रहें और फलियां बनते समय पर्याप्त नमी रखें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी रासायनिक दवा की आवश्यकता नहीं है।'
  },
  {
    classId: 'Squash___Powdery_mildew',
    cropName: 'Squash',
    cropNameHi: 'कद्दू / लौकी',
    diseaseName: 'Powdery Mildew (Podosphaera xanthii)',
    diseaseNameHi: 'कद्दू वर्गीय — चूर्णिल फफूंद (Powdery Mildew)',
    organicAction: 'Spray with dilute potassium bicarbonate or baking soda solution (1 tsp baking soda + 1 tsp horticultural oil per liter water) or Bacillus subtilis.',
    organicActionHi: 'पत्ते पर सफेद पाउडर दिखने पर 1 चम्मच मीठा सोडा + 1 चम्मच नीम तेल 1 लीटर पानी में मिलाकर छिड़कें।',
    chemicalSpray: 'Apply Myclobutanil, Triflumizole, or Pyraclostrobin at first sign of white powdery spots on lower leaf surfaces.',
    chemicalSprayHi: 'माइक्लोबुटानिल (1 मिली) या घुलनशील सल्फर (2 ग्राम प्रति लीटर पानी) का शाम के समय छिड़काव करें।'
  },
  {
    classId: 'Strawberry___Leaf_scorch',
    cropName: 'Strawberry',
    cropNameHi: 'स्ट्रॉबेरी',
    diseaseName: 'Leaf Scorch (Diplocarpon earlianum)',
    diseaseNameHi: 'स्ट्रॉबेरी — पत्ती झुलसा रोग (Leaf Scorch)',
    organicAction: 'Remove and destroy infected purple-spotted leaves after renovation. Ensure strawberry crowns are spaced for quick morning drying.',
    organicActionHi: 'बैंगनी-भूरे धब्बे वाले पुराने पत्तों को तोड़कर फेंकें। पौधों के बीच दूरी रखें ताकि सुबह की धूप से पत्ते जल्दी सूखें।',
    chemicalSpray: 'Apply Captan 50 WP or Thiram during early spring crown development before fruit emergence.',
    chemicalSprayHi: 'कैप्टान (Captan 50 WP) 2.5 ग्राम प्रति लीटर पानी में कली बनते समय छिड़कें।'
  },
  {
    classId: 'Strawberry___healthy',
    cropName: 'Strawberry',
    cropNameHi: 'स्ट्रॉबेरी',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Vibrant leaf canopy. Maintain straw bedding underneath fruit to prevent soil contact, and weed regularly.',
    organicActionHi: 'फसल पूरी तरह स्वस्थ है। फलों को जमीन से बचाने के लिए नीचे पुआल बिछाएं और नियमित निराई करें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी रासायनिक दवा की जरूरत नहीं है।'
  },
  {
    classId: 'Tomato___Bacterial_spot',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Bacterial Spot (Xanthomonas perforans)',
    diseaseNameHi: 'टमाटर — जीवाणु धब्बा रोग (Bacterial Spot)',
    organicAction: 'Prune infected lower foliage with disinfected shears (70% alcohol). Spray with organic fixed-copper and Bacillus subtilis.',
    organicActionHi: 'रोगग्रस्त निचले पत्तों को साफ कैंची से काटकर नष्ट करें। नीम का तेल (1%) या कॉपर युक्त जैविक दवा छिड़कें।',
    chemicalSpray: 'Apply copper hydroxide combined with Mancozeb spray during early morning hours to bypass bacterial stomatal entry.',
    chemicalSprayHi: 'कॉपर ऑक्सीक्लोराइड (2.5 ग्राम) + स्ट्रेप्टोसाइक्लिन (1 ग्राम प्रति 10 लीटर पानी) सुबह-सुबह छिड़कें।'
  },
  {
    classId: 'Tomato___Early_blight',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Early Blight (Alternaria solani)',
    diseaseNameHi: 'टमाटर — अगेती झुलसा (Early Blight)',
    organicAction: 'Mulch soil surface with straw or black plastic to stop soilborne spore splashback. Strip off lowest 12 inches of foliage.',
    organicActionHi: 'जमीन से सटे 10-12 इंच तक के पत्तों को हटा दें। मिट्टी पर पुआल की मल्चिंग करें ताकि मिट्टी के फफूंद पत्तों पर न उछलें।',
    chemicalSpray: 'Apply preventive Chlorothalonil or Azoxystrobin (Amistar) spray every 7–10 days during warm, humid intervals.',
    chemicalSprayHi: 'क्लोरोथैलोनिल या एमिस्टार (Azoxystrobin) 1 मिली प्रति लीटर पानी में 7 से 10 दिन पर छिड़कें।'
  },
  {
    classId: 'Tomato___Late_blight',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Late Blight (Phytophthora infestans)',
    diseaseNameHi: 'टमाटर — पछेती झुलसा (Late Blight)',
    organicAction: 'HIGH EMERGENCY: Prune out and destroy infected water-soaked shoots immediately. Discontinue overhead watering and maximize air circulation.',
    organicActionHi: '🚨 तुरंत कदम उठाएं: पानी जैसे भीगे काले तनों को तुरंत काटकर जलाएं। ऊपर से पानी छिड़कना बंद करें।',
    chemicalSpray: 'Apply systemic Metalaxyl + Mancozeb (Ridomil Gold) or Mandipropamid (Revus) every 5-7 days under cool, damp conditions.',
    chemicalSprayHi: 'रिडोमिल गोल्ड (Metalaxyl + Mancozeb) 2.5 ग्राम प्रति लीटर पानी में 5-7 दिन के अंतराल पर तुरंत छिड़कें।'
  },
  {
    classId: 'Tomato___Leaf_Mold',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Leaf Mold (Passalora fulva)',
    diseaseNameHi: 'टमाटर — पत्ती फफूंद (Leaf Mold)',
    organicAction: 'Reduce greenhouse relative humidity below 85% by opening ridge vents and running horizontal air circulation fans.',
    organicActionHi: 'पॉलीहाउस या खेत में हवा का बहाव बढ़ाएं। पत्तों के नीचे की नमी कम रखें।',
    chemicalSpray: 'Apply Chlorothalonil, Copper hydroxide, or Difenoconazole targeting the underside of leaves where olive-brown mold sporulates.',
    chemicalSprayHi: 'कॉपर हाइड्रोक्साइड या डाइफेनोकोनाज़ोल (1 मिली प्रति लीटर) पत्तों के निचले हिस्से पर छिड़कें।'
  },
  {
    classId: 'Tomato___Septoria_leaf_spot',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Septoria Leaf Spot (Septoria lycopersici)',
    diseaseNameHi: 'टमाटर — सेप्टोरिया धब्बा रोग (Septoria Leaf Spot)',
    organicAction: 'Remove bottom leaves bearing circular dark spots with light centers. Stake and prune tomatoes to maintain canopy separation.',
    organicActionHi: 'छोटे गोल धब्बे वाले निचले पत्तों को तोड़कर खेत से दूर फेंकें। पौधों को बांस-तार से सहारा दें।',
    chemicalSpray: 'Apply Chlorothalonil or Mancozeb beginning when first fruit clusters set, repeated at 7–10 day intervals.',
    chemicalSprayHi: 'मैंकोज़ेब (2.5 ग्राम प्रति लीटर) फल बनते ही छिड़कना शुरू करें और 10 दिन पर दोहराएं।'
  },
  {
    classId: 'Tomato___Spider_mites Two-spotted_spider_mite',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Two-Spotted Spider Mite (Tetranychus urticae)',
    diseaseNameHi: 'टमाटर — लाल मकड़ी कीट (Two-Spotted Spider Mite)',
    organicAction: 'Spray underside of foliage with forceful stream of water or cold-pressed neem oil (1%). Release predatory Phytoseiulus persimilis mites.',
    organicActionHi: 'पत्तों के नीचे तेज धार से पानी का छिड़काव करें। 1% नीम का तेल या साबुन का हल्का घोल छिड़कें।',
    chemicalSpray: 'Apply Abamectin, Bifenazate (Acramite), or Spiromesifen; ensure thorough coverage of leaf undersides.',
    chemicalSprayHi: 'अबामाईक्टिन (Abamectin) 0.5 मिली या ओबेरॉन (Spiromesifen) 1 मिली प्रति लीटर पानी में पत्तों के नीचे छिड़कें।'
  },
  {
    classId: 'Tomato___Target_Spot',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Target Spot (Corynespora cassiicola)',
    diseaseNameHi: 'टमाटर — लक्ष्य धब्बा (Target Spot)',
    organicAction: 'Clear decaying plant debris from beds. Avoid working in wet foliage to prevent mechanical transfer of fungal conidia.',
    organicActionHi: 'खेत में गिरे सड़े पत्तों को साफ करें। भीगे पौधों को हाथ न लगाएं ताकि रोग दूसरे पौधों में न फैले।',
    chemicalSpray: 'Apply Azoxystrobin, Fluxapyroxad + Pyraclostrobin, or Chlorothalonil at symptom onset.',
    chemicalSprayHi: 'एज़ोक्सीस्ट्रोबिन या क्लोरोथैलोनिल 2 ग्राम प्रति लीटर पानी में मिलाकर छिड़कें।'
  },
  {
    classId: 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Tomato Yellow Leaf Curl Virus (TYLCV)',
    diseaseNameHi: 'टमाटर — पीला पत्ता मरोड़िया वायरस (TYLCV)',
    organicAction: 'Eradicate whitefly vectors (Bemisia tabaci) using yellow sticky cards and reflective silver UV-reflective mulches. Destroy stunted plants.',
    organicActionHi: 'सफेद मक्खी इस रोग को फैलाती है। खेत में पीले चिपचिपे कार्ड लगाएं और मुड़े हुए पौधों को उखाड़कर नष्ट करें।',
    chemicalSpray: 'Control vectors: Apply Spirotetramat, Pyriproxyfen, or Dinotefuran targeting immature whitefly nymphs on leaf undersides.',
    chemicalSprayHi: 'सफेद मक्खी की रोकथाम: एसिटामिप्रिड (0.5 ग्राम) या थायमेथॉक्सम (0.5 ग्राम प्रति लीटर) का पत्तों के नीचे छिड़काव करें।'
  },
  {
    classId: 'Tomato___Tomato_mosaic_virus',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Tomato Mosaic Virus (ToMV)',
    diseaseNameHi: 'टमाटर — मोज़ेक वायरस (Mosaic Virus)',
    organicAction: 'Strict phytosanitary protocol: Wash hands with soap and dip tools in 20% skim milk before handling plants. Rogue out infected mottling plants.',
    organicActionHi: 'खेत में काम करने से पहले साबुन से हाथ धोएं। बीड़ी-तंबाकू खाकर पौधे न छुएं। रोगी पौधों को तुरंत उखाड़कर जला दें।',
    chemicalSpray: 'No curative chemical spray exists for plant viruses. Focus strictly on sanitation, seedling quarantine, and resistant rootstocks.',
    chemicalSprayHi: 'वायरस का कोई रासायनिक इलाज नहीं है; केवल रोगवाहक कीटों को रोकें और स्वस्थ प्रमाणित बीजों का ही प्रयोग करें।'
  },
  {
    classId: 'Tomato___healthy',
    cropName: 'Tomato',
    cropNameHi: 'टमाटर',
    diseaseName: 'Healthy Leaf',
    diseaseNameHi: 'स्वस्थ पत्ता (Healthy)',
    organicAction: 'Crop is thriving. Maintain consistent soil moisture to prevent blossom end rot, prune suckers, and provide sturdy caging.',
    organicActionHi: 'फसल बहुत अच्छी और स्वस्थ है। फल सड़न से बचाने के लिए पौधों को सहारा दें और नियमित संतुलित पानी दें।',
    chemicalSpray: 'None required.',
    chemicalSprayHi: 'किसी रासायनिक दवा की आवश्यकता नहीं है।'
  }
];
